#!/bin/sh
set -eu

root_path=$(dirname $(dirname $(readlink -f "${0}")))
tool_dir="tool"
name="google-cloud-sdk"
arch="linux-x86_64"

# https://cloud.google.com/sdk/docs/quickstart-linux
version="265.0.0"
checksum="9633769d58d757ac7888efbe704772bc41113004c428222cad692e69b8fb27b1"

package_base_url="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads"
package_file="${name}-${version}-${arch}.tar.gz"

indent() {
  sed -u 's/^/       /'
}

echo "Platform: ${arch}"
echo "Version: ${version}"
echo ""

mkdir -p $root_path/$tool_dir
cd $root_path/$tool_dir

echo "-----> Fetching into: ${root_path}/${tool_dir}"
curl -sL $package_base_url/$package_file -o $package_file

# check sha256 checksum
echo "${checksum}" "" ./$package_file | sha256sum -c - | indent

echo "-----> Deleting old sdk (if exists)"
rm -fr "./${name}"

echo "-----> Extracting new sdk"
tar zxf $package_file | indent

# setup $tool_dir as a root for sdk
echo ""
echo "{{{"
echo ""
CLOUDSDK_ROOT_DIR=. ./$name/install.sh
echo "}}}"
echo ""

cd $root_path

echo "-----> Done"

# print instructions
source_cmd="source ${root_path}/${tool_dir}/load-gcloud"
init_cmd="gcloud init"
update_cmd="gcloud components update"

echo "Run \`${source_cmd}\`" | indent
echo "Then init by \`${init_cmd}\` and update with \`${update_cmd}\`" | indent
